import Head from "next/head";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import { Montserrat, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

// Load fonts
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>WhiteLabel</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link rel="icon" href="/shopping_basket.svg" type="image/svg+xml" />
      </Head>
      <div
        className={`${montserrat.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <Component {...pageProps} />
        <Footer />
      </div>
    </>
  );
}
